### ISSUE TITLE
add POM on the default list on asset page in massa wallet

### ISSUE THREAD

**Issue by OliornPT** [bearby-wallet/cryptometa#1]
Hi,

Already spoke by Chat with Rinat that told me to open here this ticket.
Launch date is Planned for this Friday 14 november 1PM, but you can already put in Production, no problem.

Uploaded 2 pictures, One Circular and other the original , use the one that fits the best.

Smart Contract of the Token: AS1nqHKXpnFXqhDExTskXmBbbVpVpUbCQVtNSXLCqUDSUXihdWRq

Details of the FT - code used:

const token = {
name: 'PepeOnMassa',
symbol: 'POM',
decimals: 18n,
totalSupply: 10800700300n * 10n ** 18n,
};

const tokenArgs = new Args()
.addString([token.name](https://token.name/))
.addString(token.symbol)
.addU8(token.decimals)
.addU256(token.totalSupply);

![LOGO](https://github.com/user-attachments/assets/a496550a-32ce-4ed4-a643-0de612d0af2d)
![POM HAT](https://github.com/user-attachments/assets/827f5b64-78be-449f-93e7-9dda0503faf7)

**Comment by hicaru** [comment]
Hello thanks for you issue, but it should be a PR. please create a PR with all specifications required

**Comment by OliornPT** [comment]
hello  @hicaru  thank you for your message. Its now here :https://github.com/bearby-wallet/cryptometa/pull/2
